<?php

namespace Database\Seeders;

use App\Models\Configuration;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ConfigurationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $censo = [

            [
                'name' => 'ENTIDAD FEDERAL',
                'excel_cell' => 'B8',
                'required' => true,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'CÉDULA DE IDENTIDAD VENEZOLANA',
                'excel_cell' => 'C8',
                'required' => true,
                'unique' => true,
                'filterable' => false,
                'searchable' => true,
                'start_date' => false,
                'end_date' => false,
                'ci' => true,
            ],
            [
                'name' => 'N° DE PASAPORTE',
                'excel_cell' => 'D8',
                'required' => false,
                'unique' => true,
                'filterable' => false,
                'searchable' => true,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'NACIONALIDAD',
                'excel_cell' => 'E8',
                'required' => true,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'PAÍS DE ORIGEN',
                'excel_cell' => 'F8',
                'required' => true,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'APELLIDOS Y NOMBRES',
                'excel_cell' => 'G8',
                'required' => true,
                'unique' => false,
                'filterable' => false,
                'searchable' => true,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'SEXO',
                'excel_cell' => 'H8',
                'required' => true,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'FECHA DE NACIMIENTO',
                'excel_cell' => 'I8',
                'required' => true,
                'unique' => false,
                'filterable' => false,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'EDAD',
                'excel_cell' => 'J8',
                'required' => false,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'TÍTULO DE PREGRADO OBTENIDO',
                'excel_cell' => 'K8',
                'required' => true,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'UNIVERSIDAD DONDE CURSÓ EL PREGRADO',
                'excel_cell' => 'L8',
                'required' => true,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'N° DE TELÉFONO MÓVIL',
                'excel_cell' => 'M8',
                'required' => true,
                'unique' => false,
                'filterable' => false,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'E-MAIL',
                'excel_cell' => 'N8',
                'required' => true,
                'unique' => true,
                'filterable' => false,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'FECHA DE INICIO',
                'excel_cell' => 'O8',
                'required' => true,
                'unique' => false,
                'filterable' => false,
                'searchable' => false,
                'start_date' => true,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'FECHA DE CULMINACIÓN',
                'excel_cell' => 'P8',
                'required' => true,
                'unique' => false,
                'filterable' => false,
                'searchable' => false,
                'start_date' => false,
                'end_date' => true,
                'ci' => false,

            ],
            [
                'name' => 'DURACIÓN DEL POSTGRADO',
                'excel_cell' => 'Q8',
                'required' => false,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'CENTRO ASISTENCIAL',
                'excel_cell' => 'R8',
                'required' => true,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'ESPECIALIDAD',
                'excel_cell' => 'S8',
                'required' => true,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'UNIVERSIDAD O INSTITUCIÓN QUE CERTIFICA',
                'excel_cell' => 'T8',
                'required' => true,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'RAPCCE',
                'excel_cell' => 'U9',
                'required' => false,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'FELLOW',
                'excel_cell' => 'V9',
                'required' => false,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'PNFA',
                'excel_cell' => 'W9',
                'required' => false,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'POSTGRADO',
                'excel_cell' => 'X9',
                'required' => false,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'MAESTRÍA',
                'excel_cell' => 'Y9',
                'required' => false,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'R1',
                'excel_cell' => 'Z9',
                'required' => false,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'R2',
                'excel_cell' => 'AA9',
                'required' => false,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'R3',
                'excel_cell' => 'AB9',
                'required' => false,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'R4',
                'excel_cell' => 'AC9',
                'required' => false,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'R5',
                'excel_cell' => 'AD9',
                'required' => false,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'RR',
                'excel_cell' => 'AE9',
                'required' => false,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'TRASLADO FÍSICO (ENTIDAD FEDERAL DE PROCEDENCIA)',
                'excel_cell' => 'AF8',
                'required' => false,
                'unique' => false,
                'filterable' => true,
                'searchable' => false,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
        ];

        $renuncias = [
            [
                'name' => 'Nombre y apellido',
                'excel_cell' => 'A4',
                'required' => true,
                'unique' => false,
                'filterable' => true,
                'searchable' => true,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'Cédula',
                'excel_cell' => 'B4',
                'required' => true,
                'unique' => true,
                'filterable' => true,
                'searchable' => true,
                'start_date' => false,
                'end_date' => false,
                'ci' => true,
            ],
            [
                'name' => 'Especialidad',
                'excel_cell' => 'C4',
                'required' => true,
                'unique' => false,
                'filterable' => true,
                'searchable' => true,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ],
            [
                'name' => 'Universidad que certifica',
                'excel_cell' => 'D4',
                'required' => true,
                'unique' => false,
                'filterable' => true,
                'searchable' => true,
                'start_date' => false,
                'end_date' => false,
                'ci' => false,
            ]
        ];

        Configuration::create([
            'name' => 'Censo de residentes',
            'structure' => $censo
        ]);

        Configuration::create([
            'name' => 'Renuncias',
            'structure' => $renuncias
        ]);
    }
}
